### ISSUE TITLE
My napkin is on the floor...

### ISSUE THREAD

**Issue by ronkerensky** [BarkSoftware/beer-napkin#11]
I saved it, got out of BN and came back and there seems to be no way to retrieve a previously  created napkin

**Comment by ronkerensky** [comment]
I see that I should be able to click on it from the Git or waffle issue, but it just clocks.

**Comment by ronkerensky** [comment]
![image](https://cloud.githubusercontent.com/assets/4391647/16266558/879f1848-3853-11e6-9039-51404c0dacf8.png)

**Comment by ronkerensky** [comment]
This happened eventually.

**Comment by ronkerensky** [comment]
I think I figured out the link part... it's using port 3508 in the link. When I manually change the link from: http://beernapkin.com:3508/napkins/4/edit
to: http://beernapkin.com/napkins/4/edit
it works fine.  I think we should also have previously saved napkins on the home screen (once logged in), too.

**Comment by brandonjoyce** [comment]
Fixed.  Was just a configuration issue.
